### ISSUE TITLE
Issues on linux

### ISSUE THREAD

**Issue by slidinghotdog** [nodegui/nodegui-plugin-webview#2]
@master-atul are u currently working on this? if not at least this might serve as a future reference..
I have some issues trying this on linux, installed `Qt5.13.0` and `QT_INSTALL_DIR` is set 

Here are the issues and what i tried:
- asks for `checkIfNativeElement` and `QUrl`

updated nodegui version on `package.json`
- asks for libraries

corrected filenames on `qtweb.cmake` to `"${QT_HOME_DIR}/lib/libQt5WebEngine.so"` and   `"${QT_HOME_DIR}/lib/libQt5WebEngineWidgets.so"`

- Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.

rebuilt qode adding this line before `new QApplication`: `  QCoreApplication::setAttribute(Qt::AA_ShareOpenGLContexts,true);`
then copied to  to `node_modules/@nodegui/qode/dist/1.0.6`

- QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled

copied manually (don't know how to change config files to include in plugin Release)
`plugins/xcbglintegrations` from ` gcc_64` to `node_modules/@nodegui/qode/dist/1.0.6`

- Could not find QtWebEngineProcess

copied `libexec` dir

- after that some errors about resources and translations

copied `resources` and `translations/qtwebengine_locales`

now the demo runs without warnings but webview doesn't show (it flashes image from some electron app i have running, not sure if its related) and only logs `http://google.com/ Url from webview`.

then i copied entire `includes` and `lib` folders from  `gcc_64` to  `node_modules/@nodegui/qode/dist/1.0.6` and it worked, tried copying only a few different modules but i couldn't figure out what was missing.

this is what it looks like without last step:
![ksnip_20191217-203606](https://user-images.githubusercontent.com/33790211/71043276-ebf13880-210c-11ea-9c67-18b5cfdb0179.png)

**Comment by master-atul** [comment]
This is now fixed in the latest update. 
Although it doesnt mean its close to completion and there would be bugs.

But if you try it now. It should just work :) 
Closing this now.

**Comment by master-atul** [comment]
Thanks for checking this out!
