### ISSUE TITLE
No packages published?

### ISSUE THREAD

**Issue by jardenliu** [nodegui/nodegui-plugin-webview#6]

**Comment by a7ul** [comment]
This package is now published on the npm :)

**Comment by jardenliu** [comment]
The latest release package does not contain the `.node` file.
Get some error as follow:
```bash
Error: Cannot find module '../build/Release/nodegui_plugin_webview_init.node'
Require stack:
- /Users/jarden/workspace/nodegui-plugin-webview-bridge/node_modules/nodegui-plugin-webview/dist/index.js
- /Users/jarden/workspace/nodegui-plugin-webview-bridge/dist/demo.js
```

![image](https://user-images.githubusercontent.com/15191056/91695870-6087dc80-eba1-11ea-9c3b-39b82b69eda5.png)

Didn't exec `npm run build` before publishing?

**Comment by a7ul** [comment]
My bad. https://github.com/nodegui/nodegui-plugin-webview/pull/9
